project:
  type: book
  output-dir: docs

book:
  title: "How Does My &#x1F92C; Computer Work"
  author: "Mike Mull"
  date: "9/2/2024"
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - hdmcw-prank.qmd
    - hdmcw-memory.qmd
    - hdmcw-programs.qmd
    - hdmcw-virtual.qmd
    - hdmcw-processes.qmd
    - hdmcw-cores.qmd
    - hdmcw-threads.qmd
    - hdmcw-scheduler.qmd
    - hdmcw-io.qmd
    - references.qmd
    - --

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


